//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sgate.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class cliente
    {
        [Display(Name = "Código")]
        public int idcliente { get; set; }
        [Required]
        [Display(Name = "Nome")]
        public string nome { get; set; }
        [Required]
        [Display(Name = "CPF")]
        public string cpf { get; set; }
        [Required]
        [Display(Name = "Logradouro")]
        public string logradouro { get; set; }
        [Required]
        [Display(Name = "Número")]
        public Nullable<int> numero { get; set; }
        [Required]
        [Display(Name = "Bairro")]
        public string bairro { get; set; }
        [Required]
        [Display(Name = "Cidade")]
        public string cidade { get; set; }
        [Required]
        [Display(Name = "UF")]
        public string uf { get; set; }
        [Required]
        [Display(Name = "Email")]
        public string email { get; set; }
    }
}
