//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sgate.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class cliente
    {
        [Required]
        [Display(Name = "Código")]
        public int idcliente { get; set; }

        [Required(ErrorMessage = "Campo Obrigatório")]
        [Display(Name = "Nome")]
        [StringLength(250, ErrorMessage = "Campo permite somente 250 caracteres")]
        public string nome { get; set; }

        [Required(ErrorMessage = "Campo Obrigatório")]
        [Display(Name = "CPF")]
        [StringLength(11, ErrorMessage = "Campo permite somente 11 caracteres")]
        public string cpf { get; set; }

        [Required(ErrorMessage = "Campo Obrigatório")]
        [Display(Name = "Logradouro")]
        [StringLength(250, ErrorMessage = "Campo permite somente 250 caracteres")]
        public string logradouro { get; set; }

        [Required(ErrorMessage = "Campo Obrigatório")]
        [Display(Name = "Número")]
        public Nullable<int> numero { get; set; }

        [Required(ErrorMessage = "Campo Obrigatório")]
        [Display(Name = "Bairro")]
        [StringLength(50, ErrorMessage = "Campo permite somente 50 caracteres")]
        public string bairro { get; set; }

        [Required(ErrorMessage = "Campo Obrigatório")]
        [Display(Name = "Cidade")]
        [StringLength(50, ErrorMessage = "Campo permite somente 50 caracteres")]
        public string cidade { get; set; }

        [Required(ErrorMessage = "Campo Obrigatório")]
        [Display(Name = "UF")]
        [StringLength(2, ErrorMessage = "Campo permite somente 2 caracteres")]
        public string uf { get; set; }

        [Required(ErrorMessage = "Campo Obrigatório")]
        [Display(Name = "E-mail")]
        //[EmailAddress]
        [DataType(DataType.EmailAddress, ErrorMessage = "E-mail informado inválido")]
        [StringLength(250, ErrorMessage = "Campo permite somente 250 caracteres")]
        public string email { get; set; }
    }
}
