//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sgate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class itenspacote
    {
        public int idItemPacote { get; set; }
        public Nullable<int> idPacote { get; set; }
        public Nullable<int> idproduto { get; set; }
    
        public virtual pacote pacote { get; set; }
        public virtual produto produto { get; set; }
    }
}
