//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sgate.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class itenspacote
    {

        public int iditempacote { get; set; }
        public Nullable<int> idpacote { get; set; }
        public Nullable<int> idproduto { get; set; }

        public virtual pacote pacote { get; set; }
        public virtual produto produto { get; set; }
    }
}
