//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sgate.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sgateEntities : DbContext
    {
        public sgateEntities()
            : base("name=sgateEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<pacote> pacote { get; set; }
        public DbSet<produto> produto { get; set; }
        public DbSet<tipoproduto> tipoproduto { get; set; }
        public DbSet<cliente> cliente { get; set; }
        public DbSet<itenspacote> itenspacote { get; set; }
    }
}
