//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sgate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pacote
    {
        public pacote()
        {
            this.itenspacote = new HashSet<itenspacote>();
        }
    
        public int idpacote { get; set; }
        public string pacote1 { get; set; }
    
        public virtual ICollection<itenspacote> itenspacote { get; set; }
    }
}
