//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sgate.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class produto
    {
        public produto()
        {
            this.itenspacote = new HashSet<itenspacote>();
        }
        
        [Display(Name = "Código")]
        public int idproduto { get; set; }
        
        [Required]
        [Display(Name = "Descriçao")]
        public string descricao { get; set; }
        
        [Required]
        [Display(Name = "Data de Expiração")]
        public Nullable<System.DateTime> dataexpiracao { get; set; }
        
        [Required]
        [Display(Name = "Valor")]
        public Nullable<decimal> valorproduto { get; set; }
        
        [Required]
        [Display(Name = "Tipo de Produto")]
        public Nullable<int> idtipo { get; set; }

        public virtual tipoproduto tipoproduto { get; set; }
        public virtual ICollection<itenspacote> itenspacote { get; set; }
    }
}
