//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sgate.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class produto
    {
        public produto()
        {
            this.itenspacote = new HashSet<itenspacote>();
        }

        [Required]
        [Display(Name = "Código")]
        public int idproduto { get; set; }

        [Required(ErrorMessage = "Campo Obrigatório")]
        [Display(Name = "Descrição")]
        public string descricao { get; set; }

        [Required(ErrorMessage = "Campo Obrigatório")]
        [Display(Name = "Data Expiração")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        public Nullable<System.DateTime> dataexpiracao { get; set; }

        [Required(ErrorMessage = "Campo Obrigatório")]
        [Display(Name = "Valor")]
        [Range(0.01, 999.99, ErrorMessage = "Valor informado inválido")]
        [DisplayFormat(DataFormatString = "{0:C2}")]
        public Nullable<decimal> valorproduto { get; set; }

        [Required(ErrorMessage = "Campo Obrigatório")]
        [Display(Name = "Tipo do Produto")]
        public Nullable<int> idtipo { get; set; }

        public virtual ICollection<itenspacote> itenspacote { get; set; }
        public virtual tipoproduto tipoproduto { get; set; }
    }
}
